name:  "Complex-work-exercise-2nd"
run-name: ${{ github.actor }} executing exercise
env:
  ENV_AT_WORKFLOW_LVL: 'env from Worklow'
on:
  push:
    branches:
      - "main01"
      - "master01"

jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: step01
        uses: actions/checkout@v
      - name: step02
        run: | 
          echo "*** Running Complex-work-exercise-2nd Ubuntu *****"
          echo "Output 1.  ${{ env.ENV_AT_WORKFLOW_LVL }} "
          echo "Output 2." env
          date
  job02:
    runs-on: windows-latest
    needs: job01
    steps:
      - name: step01
        uses: actions/checkout@v2
      - name: step02
        run: |
          echo "*** Running Complex-work-exercise-2nd Windows*****" 
          Get-ChildItem Env: | Sort-Object Name
          Get-Date

      
