name: GitHubAction first
run-name: ${{ github.actor }} is tetsing out GitHub Actions
on: [push]
jobs:
  job01:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        uses: actions/checkout@v2
      - name: step2
        run: env | sort
  job02:
    runs-on: windows-latest
    steps:
      - name: step01
        uses: actions/checkout@v2
      - name: step02
        run: "Get-ChildItem Env: | Sort-Object Name"
      
       
  